### ISSUE TITLE
Bitrate Tooltip Question

### ISSUE THREAD

**Issue by edleatherbury** [twilio/twilio-video-diagnostics-react-app#22]
This app has been very helpful while developing our own WebRTC diagnostics page. I do have a question about the bitrate tooltip in the quality information dialog. It says this: 

"Bitrate is the way we measure the speed of the upload and download transfers. If a sender uploads data too quickly and exceeds the transfer speed, the network gets overwhelmed and can cause issues for everyone. Symptoms of this can be frozen video, downscaled video, frame-rate drops, choppy audio, and potentially dropped connections."

Is uploading data too quickly really an issue? By far the more common issue for our users is a connection that is too slow. If a fast upload is potentially problematic, should it be throttled at the client?
<img width="927" alt="Screen Shot 2021-11-01 at 1 10 16 PM" src="https://user-images.githubusercontent.com/1591298/139711667-05276362-40bc-41de-a6f4-8ee2170ca6e7.png">

**Comment by seancoleman2** [comment]
@edleatherbury thanks for the question and happy this app has been helpful in your development!

We conducted some user testing and since the app is for end-users (who may not be technical) we tried to simplify the copy as much as possible, at the expense of exhaustiveness.  

The app uses [RTCDiagnosticsSDK](https://github.com/twilio/rtc-diagnostics)'s `testMediaConnectionBitrate` for this bitrate value. This can be used to estimate limitations in the user's available bandwidth (you don't have control over), which can help you determine a target bitrate (which you do have control over). Whether you want to use all the available bandwidth and how you want to use it depends on your use case / UX / and a lot of other factors, but oftentimes you want to strike a balance between conserving client resources (high bitrates can tax the device's CPU leading to dropped frames, for example) and quality. Practically speaking, you are right that oftentimes the issue is limitations in the end-users available bandwidth, but using it all doesn't always increase quality and it can potentially introduce decreases in quality.

I'd recommend taking a look at this guide on [Developing High Quality Video Applications](https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications) for more info, if you haven't done so already. 

Hope that helps. 

We also are looking for feedback on this application (or the underlying Preflight API / RTCDiagnosticsSDK). If you'd be open to chatting more, you can reach me at scoleman at twilio.com. I'd also be interested to see how you customized it for your service!

**Comment by edleatherbury** [comment]
@seancoleman2 Thanks for the response, the tooltip verbiage makes sense now. We currently limit `maxAudioBitrate` and 'maxSubscriptionBitrate', but do not modify or limit `maxVideoBitrate`. We're following the Twilio documentation that says "the bitrate is only limited by the Twilio client SDK using an algorithm that considers the available bandwidth and CPU resources. In general, we recommend trusting that algorithm".
Thanks again, and I'll contact you directly with details on our implementation.
