### ISSUE TITLE
Invalid access token when deploying on this application on heroku

### ISSUE THREAD

**Issue by jeffss99** [twilio/twilio-video-diagnostics-react-app#32]
I have deployed this code on heroku and it is giving me error invalid access token I have double check account sid and auth token are correct.
`2.4eb97410.chunk.js:2 2022-02-16T17:03:51.152Z warn [TwilioConnection #1: wss://global.vss.twilio.com/signaling] Closed: 1002 - Invalid Access Token`
this work properly on serverless but i want to deploy on heroku on on our own server. 
Here is the link of app.
https://mcpreflight.herokuapp.com/

**Comment by olipyskoty** [comment]
Hey @jeffss99 sorry to hear that you are having some issues deploying the app to Heroku. Sounds like you are getting the web app deployed just fine, but it's having trouble talking to the backend to get an access token.

In order to assist, we will need some more information from you. Do you mind sharing what server code you are deploying to Heroku, and how are you deploying it? Can you provide some sample code?

This will help us diagnose the issue and hopefully come up with a solution to get this deployed.

Thank you!

**Comment by jeffss99** [comment]
Hi @olipyskoty  Thanks for responding , I have created a public repo of code I am using
https://github.com/jeffss99/twilio-video-diagnostics-react-app-heroku
I have also added a section how to deploy on heroku and how to set .env on heroku.
Please let me know if you need anything more I can share heroku app as well.
Thanks

**Comment by jeffss99** [comment]
On further investigating it seems like It does not work in following cases
`without proxy URL`
`npm run build`
But it wok on local system with
`npm run dev`

**Comment by olipyskoty** [comment]
Hey @jeffss99! Looks like you're trying to use the `/serverless` code for your server when you deploy to Heroku. Unfortunately, this code is meant to be used to deploy serverless endpoints to the Twilio Serverless environment, which is why you're receiving the Invalid Access Token error. It won't work with a different platform. 

You'd need to create your own server code that generates a Twilio Access Token (which would also be used to obtain TURN credentials to start the bitrate test) in order to host your application somewhere other than Twilio. Your question actually inspired us to add this server code to the Video Diagnostics App so that customers like you can easily host their applications outside of Twilio. I have added a ticket to our internal backlog and this should be available in the near future. I'll keep you posted 🙂. 

In the meantime, and if you'd like to get a head start, check out the node `/server` code from our [Twilio Video React App](https://github.com/twilio/twilio-video-app-react/tree/master/server). A lot of the code in `index.ts` and `createExpressHandler.ts` can be copied over, just remember that we won't need anything "conversations" or "recordingRules" related. Also, instead of `require('@twilio-labs/plugin-rtc/src/serverless/functions/token').handler` in `index.ts`, you can point to the `/token` and `/turn-credentials` files in the `/serverless` directory.

I'll respond to this question when the new `/server` code has been merged. Please let us know if you have any other questions!

**Comment by shawnmintz** [comment]
Hello, @olipyskoty thanks for your help with this. From our understanding to host the diagnostic tool on Twilio, there is a 7-day limit for it being live. Is there a way to extend this?

**Comment by olipyskoty** [comment]
Hey @jeffss99 and @shawnmintz! 

Wanted to let you know about a couple of updates.

Firstly, we have added a new token server to this application (can be found in [/server](https://github.com/twilio/twilio-video-diagnostics-react-app/tree/main/server)). This server uses the same endpoints as the [serverless](https://github.com/twilio/twilio-video-diagnostics-react-app/tree/main/serverless/functions/app) endpoints that are used when the app is deployed to Twilio Serverless. You can use this server to run the app locally by running the `npm start` command, but you can also use it for deployment purposes outside of Twilio Serverless! To set up this token server, please follow the instructions in the [README](https://github.com/twilio/twilio-video-diagnostics-react-app/blob/main/README.md#running-a-local-token-server).

Secondly, we have updated the application so that the passcode expiration date can now be edited when the app is deployed to Twilio Serverless. However, please note that we decided to set it to one week for security reasons (the numeric passcode is weak and could be guessed). Also, the quick deploy feature is only meant to be used for demo purposes.

To update the passcode expiration date, you'll need to login into the Twilio Console and navigate to the Functions editor (Functions > Services > YOUR_UNIQUE_SERVICE_NAME). Note, if you do not see the "Functions" product in the menu on the left, click on Explore Products > Developer tools > Functions > Manage Services. With this editor, you can edit the live token server and change environment variables. Click on Settings on the left, and then Environment Variables. Then you can edit the API_PASSCODE_EXPIRY variable, like this:
![Screen Shot 2022-03-30 at 5 05 09 PM](https://user-images.githubusercontent.com/77076398/160950390-94efc05c-cb13-42e9-bb47-fce798b8e600.png)


The API_PASSCODE_EXPIRY is the time that the passcode will expire, represented as the number of milliseconds that have passed since 1-1-1970. Simply change this number to whatever value you want.

Hopefully all of that helps you both out, but please let me know if you have any questions! Thank you!
